#pragma once

#define NCL_MOUSE_BUTTON_1         0
#define NCL_MOUSE_BUTTON_2         1
#define NCL_MOUSE_BUTTON_3         2
#define NCL_MOUSE_BUTTON_4         3
#define NCL_MOUSE_BUTTON_5         4
#define NCL_MOUSE_BUTTON_6         5
#define NCL_MOUSE_BUTTON_7         6
#define NCL_MOUSE_BUTTON_8         7
#define NCL_MOUSE_BUTTON_LAST      NCL_MOUSE_BUTTON_8
#define NCL_MOUSE_BUTTON_LEFT      NCL_MOUSE_BUTTON_1
#define NCL_MOUSE_BUTTON_RIGHT     NCL_MOUSE_BUTTON_2
#define NCL_MOUSE_BUTTON_MIDDLE    NCL_MOUSE_BUTTON_3